name: "Eric Price"
markdown: kramdown
highlighter: rouge
permalink: /blog/:title/
paginate: 10
paginate_path: "/blog/page:num"
twitter_username: ericprice2
github_username:  eric-price
url: "http://eric-price.net"
title: "Eric Price"
# exclude: [node_modules, scss]

sass:
    sass_dir: _sass
    style: :compressed
